### ISSUE TITLE
Breaking changes with Coq 8.5~beta3

### ISSUE THREAD

**Issue by clarus** [amintimany/UniverseComparator#3]
The package [coq:universe-comparator.1.0.1](http://coq.io/opam/coq:universe-comparator.1.0.1.html) does not compile on the new `8.5~beta3` version of Coq: [bench results](https://coq-bench.github.io/clean/Linux-x86_64-4.02.2-1.2.2/released/8.5~beta3/universe-comparator/1.0.1.html). I updated the dependencies [here](https://github.com/coq/opam-coq-archive/commit/1ff72610f6211d91d29479dbdeaab687e391e730).

Note: the beta3 of Coq is only available through OPAM for now, on the `released` repository (should be move to the `core-dev` repository soon).

**Comment by clarus** [comment]
To add the `core-dev` repository with Coq 8.5 beta3:

```
opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
```

**Comment by amintimany** [comment]
Hi @clarus,

I just added the new version which fixes this compatibility issue to my clone of opam-coq-archive, [here](https://github.com/amintimany/opam-coq-archive/commit/5758c6e95be7677b02df4fa999a181e86c4bdbc3).
This new version solves the problem. However in my local testings with opam, I had two problems:

First, running opam-admin make on released repository gives the error that the files given for repositories coq:force84 and coq:force85 are not tar.gz files (they are apparently .jpg images)

Second, (this might be related to the previous problem of not having a completely successful "oapm-admin make") in my local tests despite having pinned the coq version to beta3 it still tries to compile and install the older version of universe-comparator which clearly says in its compatibility '< "8.5~beta3"' (this was changed in the commit mentioned in the issue report).

Hence I'm not sure if I should make a pull request to opam-coq-archive with the aforementioned commit.

**Comment by clarus** [comment]
I am currently on the train so my Internet is not so good, but your repository seems to work. So your second issue may be related to the first. It is not necessary to run `opam-admin` to add a local repository, you can directly run on a fresh OPAM archive:

```
opam repo add released /a/b/c/opam-coq-archive/released
opam repo add core-dev /a/b/c/opam-coq-archive/core-dev
```

Still, I should correct the `.tar.gz` issue of the `coq:force-84` and `coq:force-85` packages.
